CREATE TABLE IF NOT EXISTS BANK
(
   `ID` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
   `NAME` VARCHAR (300) NOT NULL,
   `CODE` VARCHAR (300) NOT NULL UNIQUE,
   `ADDRESS` VARCHAR (300) NOT NULL,
   `PHONE_NUMBER` VARCHAR (20) NULL,
   `EMAIL` VARCHAR (300) NOT NULL UNIQUE,
   PRIMARY KEY (ID)
);