CREATE TABLE IF NOT EXISTS USER
(
   `ID` BIGINT NOT NULL AUTO_INCREMENT,
   `USERNAME` VARCHAR (20) NOT NULL UNIQUE,
   `PASSWORD` VARCHAR (300) NOT NULL UNIQUE,
   `ROLE` VARCHAR (20) NOT NULL,
   PRIMARY KEY (ID)
);