CREATE TABLE IF NOT EXISTS PAYMENT
(
   `ID` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
   `ACCOUNT_NUMBER` VARCHAR (300) NOT NULL,
   `ACCOUNT_HOLDER_NAME` VARCHAR (300) NOT NULL,
   `TRANSACTION_AMOUNT` DOUBLE
   (
      10,
      2
   )
   NOT NULL,
   `BANK_NAME` VARCHAR (20) NOT NULL,
   `DATE_TIME` DATETIME NOT NULL,
   PRIMARY KEY (ID)
);